/**
 * Expo config plugin: give the Android RELEASE build a real signing config.
 *
 * `android/` is generated by prebuild and gitignored, so this can't be committed once and
 * left alone. Expo's template signs `release` with the throwaway debug keystore; this
 * rewrites `android/app/build.gradle` to add a `release` config from Gradle properties:
 *
 *   AEE_UPLOAD_STORE_FILE / _STORE_PASSWORD / _KEY_ALIAS / _KEY_PASSWORD
 *
 * (pass them in CI as `ORG_GRADLE_PROJECT_*`). Absent, it falls back to the debug keystore
 * so local release builds keep working with no keystore set up.
 */
const { withAppBuildGradle } = require('@expo/config-plugins');

const MARKER = 'AEE_UPLOAD_STORE_FILE';

function addReleaseSigningConfig(contents) {
	if (contents.includes(MARKER)) {
		return contents; // already patched (idempotent across re-runs)
	}

	const releaseConfig = [
		'        release {',
		"            if (project.hasProperty('AEE_UPLOAD_STORE_FILE')) {",
		'                storeFile file(AEE_UPLOAD_STORE_FILE)',
		'                storePassword AEE_UPLOAD_STORE_PASSWORD',
		'                keyAlias AEE_UPLOAD_KEY_ALIAS',
		'                keyPassword AEE_UPLOAD_KEY_PASSWORD',
		'            } else {',
		'                // No upload keystore configured: fall back to debug signing so',
		'                // local release builds still work.',
		"                storeFile file('debug.keystore')",
		"                storePassword 'android'",
		"                keyAlias 'androiddebugkey'",
		"                keyPassword 'android'",
		'            }',
		'        }',
	].join('\n');

	// 1. Declare the `release` signing config inside the existing signingConfigs block.
	let next = contents.replace(
		/signingConfigs\s*\{/,
		(match) => `${match}\n${releaseConfig}`,
	);

	// 2. Point the release buildType at it, anchored so the debug buildType is untouched.
	next = next.replace(
		/(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
		'$1signingConfig signingConfigs.release',
	);

	return next;
}

const withAndroidSigning = (config) => {
	config = withAppBuildGradle(config, (cfg) => {
		if (cfg.modResults.language === 'groovy') {
			cfg.modResults.contents = addReleaseSigningConfig(
				cfg.modResults.contents,
			);
		} else {
			throw new Error(
				'withAndroidSigning: expected android/app/build.gradle to be Groovy; cannot patch.',
			);
		}
		return cfg;
	});
	return config;
};

module.exports = withAndroidSigning;
