/**
 * Expo config plugin: give the Android RELEASE build a real signing config.
 *
 * `android/` is generated by `expo prebuild` (CNG) and gitignored, so the release
 * signing config can't be committed once and left alone — it has to be re-applied on
 * every prebuild. Expo's template signs the `release` buildType with the throwaway
 * `debug` keystore; this plugin rewrites `android/app/build.gradle` to add a `release`
 * signing config sourced from Gradle properties and points the release buildType at it.
 *
 * The credentials come from these Gradle properties (pass them in CI as
 * `ORG_GRADLE_PROJECT_AEE_UPLOAD_*` env vars, or put them in ~/.gradle/gradle.properties):
 *   AEE_UPLOAD_STORE_FILE      path to the keystore, relative to android/app
 *   AEE_UPLOAD_STORE_PASSWORD  keystore password
 *   AEE_UPLOAD_KEY_ALIAS       key alias
 *   AEE_UPLOAD_KEY_PASSWORD    key password
 *
 * When they're absent the release config FALLS BACK to the debug keystore, so local
 * `./gradlew assembleRelease` / `assembleDebug` keep working with no keystore set up.
 *
 * Mirrors the existing `withSumUp` plugin's approach of patching the generated Groovy
 * build.gradle via regex.
 */
const { withAppBuildGradle } = require('@expo/config-plugins');

// Marker used both to build the injected block and to detect an already-patched file.
const MARKER = 'AEE_UPLOAD_STORE_FILE';

function addReleaseSigningConfig(contents) {
	if (contents.includes(MARKER)) {
		return contents; // already patched (idempotent across re-runs)
	}

	const releaseConfig = [
		'        release {',
		"            if (project.hasProperty('AEE_UPLOAD_STORE_FILE')) {",
		'                storeFile file(AEE_UPLOAD_STORE_FILE)',
		'                storePassword AEE_UPLOAD_STORE_PASSWORD',
		'                keyAlias AEE_UPLOAD_KEY_ALIAS',
		'                keyPassword AEE_UPLOAD_KEY_PASSWORD',
		'            } else {',
		'                // No upload keystore configured: fall back to debug signing so',
		'                // local release builds still work.',
		"                storeFile file('debug.keystore')",
		"                storePassword 'android'",
		"                keyAlias 'androiddebugkey'",
		"                keyPassword 'android'",
		'            }',
		'        }',
	].join('\n');

	// 1. Declare the `release` signing config inside the existing signingConfigs block.
	let next = contents.replace(
		/signingConfigs\s*\{/,
		(match) => `${match}\n${releaseConfig}`,
	);

	// 2. Point the release buildType at it. Anchor on `buildTypes { ... release {`
	//    so we don't touch the debug buildType's `signingConfigs.debug` reference.
	next = next.replace(
		/(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
		'$1signingConfig signingConfigs.release',
	);

	return next;
}

const withAndroidSigning = (config) => {
	config = withAppBuildGradle(config, (cfg) => {
		if (cfg.modResults.language === 'groovy') {
			cfg.modResults.contents = addReleaseSigningConfig(
				cfg.modResults.contents,
			);
		} else {
			throw new Error(
				'withAndroidSigning: expected android/app/build.gradle to be Groovy; cannot patch.',
			);
		}
		return cfg;
	});
	return config;
};

module.exports = withAndroidSigning;
