import axios, {
	type AxiosError,
	type AxiosInstance,
	type InternalAxiosRequestConfig,
} from 'axios';
import { type Document, OpenAPIClientAxios } from 'openapi-client-axios';
import { API_BASE_URL } from '@/constants/api';
import { USER_AGENT } from '@/constants/app';
import { ApiError, toApiError } from './errors';
import type { Client } from './openapi';
import { apiSession } from './session';
import spec from './spec.json';

/** Header the API scopes every tenant-owned resource by (absent from the OpenAPI doc). */
const TENANT_HEADER = 'X-Tenant-Id';

/** A request we've already retried after refreshing, so a second 401 can't loop. */
interface RetriableConfig extends InternalAxiosRequestConfig {
	_retriedAfterRefresh?: boolean;
}

/**
 * Must NOT carry `X-Tenant-Id`: these are how the app discovers which tenants exist, and a
 * stale one would 403 the very calls needed to recover.
 */
const TENANT_FREE_PATHS = ['/me', '/me/tenants', '/tenants/join'];

const isTenantFree = (url: string | undefined): boolean =>
	TENANT_FREE_PATHS.includes((url ?? '').split('?')[0]);

/**
 * Built here rather than by openapi-client-axios so the interceptors live on it and the
 * base URL comes from .env — the OpenAPI document declares no `servers`.
 */
function createAxiosInstance(): AxiosInstance {
	const instance = axios.create({
		baseURL: API_BASE_URL,
		timeout: 15_000,
		// Left unset, iOS sends NSURLSession's default, which reports the build number
		// rather than the app version.
		headers: { Accept: 'application/json', 'User-Agent': USER_AGENT },
	});

	// Stamped at send time, so a refreshed token or a tenant switch needs no re-wiring.
	instance.interceptors.request.use(async (config) => {
		// Renew before it lapses: cheaper than a 401-then-replay, and it keeps a slow
		// payment's confirmation off a dead token.
		if (apiSession.isExpiring()) {
			await apiSession.refresh();
			// Renewal failed and cleared the session: the request could only 401. (A refresh
			// that merely couldn't run leaves the token in place and falls through.)
			if (!apiSession.getAccessToken()) {
				throw new ApiError('Session expirée. Reconnectez-vous.', 401);
			}
		}
		const token = apiSession.getAccessToken();
		if (token) {
			config.headers.set('Authorization', `Bearer ${token}`);
		}
		const tenantId = apiSession.getTenantId();
		if (tenantId && !isTenantFree(config.url)) {
			config.headers.set(TENANT_HEADER, tenantId);
		}
		return config;
	});

	instance.interceptors.response.use(
		(response) => response,
		async (error: AxiosError) => {
			const config = error.config as RetriableConfig | undefined;
			// Refresh once and replay. The refresh is de-duplicated in apiSession, so a burst
			// of parallel 401s costs one token exchange.
			if (
				error.response?.status === 401 &&
				config &&
				!config._retriedAfterRefresh
			) {
				const token = await apiSession.refresh();
				if (token) {
					config._retriedAfterRefresh = true;
					config.headers.set('Authorization', `Bearer ${token}`);
					return instance.request(config);
				}
			}
			// Everything leaving the client is an ApiError — callers never see axios.
			return Promise.reject(toApiError(error));
		},
	);

	return instance;
}

/**
 * The typed client: one method per `operationId` (`api.listGrids()`,
 * `api.createOrder(null, body)`, …). Built with `initSync` — the document is a local
 * object, so there is no async startup step. See CLAUDE.md to regenerate it.
 */
export const api = new OpenAPIClientAxios({
	definition: spec as unknown as Document,
	axiosInstance: createAxiosInstance(),
	// The document is generated by NestJS and already valid; skipping validation keeps
	// app start-up cheap on device.
	quick: true,
}).initSync<Client>();
